import type { Email } from "./types";

export const SEED_EMAILS: Email[] = [
  {
    id: "e1",
    from: "Maria Chen <maria.chen@northwindco.com>",
    subject: "Webhook events stopped firing this morning",
    body: "Hi team,\n\nOur production webhook for order.completed has been silent since 08:14 UTC. We've validated the endpoint and it's responding 200 to test pings, so it looks like something on your side. This is blocking our fulfillment pipeline — could someone take a look?\n\nAccount: northwindco-prod\nLast received event id: evt_8f2a1c\n\nThanks,\nMaria",
    receivedAt: "2026-05-10T08:42:00Z",
    category: "uncategorized",
    confidence: 0,
    status: "new",
  },
  {
    id: "e2",
    from: "Devon Park <dpark@orbitalretail.io>",
    subject: "Quick question — Enterprise tier pricing for 40 seats",
    body: "Hey,\n\nWe're evaluating AgentDesk against two competitors and need final pricing for a 40-seat Enterprise plan with SSO and the audit log add-on. Can you send a quote and a sample MSA today? Decision call is Tuesday.\n\n— Devon, Head of Ops, Orbital Retail",
    receivedAt: "2026-05-10T07:15:00Z",
    category: "uncategorized",
    confidence: 0,
    status: "new",
  },
  {
    id: "e3",
    from: "billing@stripe-receipts.com",
    subject: "Invoice INV-20260501 — past due",
    body: "Hello,\n\nThis is a reminder that invoice INV-20260501 for $1,840.00 became past due on May 8th. Your card on file (Visa ending 4421) was declined twice. Please update your payment method to avoid service interruption on May 14th.\n\nAgentDesk Billing",
    receivedAt: "2026-05-10T06:02:00Z",
    category: "uncategorized",
    confidence: 0,
    status: "new",
  },
  {
    id: "e4",
    from: "winners@luxury-rewards-club.biz",
    subject: "🎉 You've been selected — claim your $500 gift card now!!",
    body: "CONGRATULATIONS!!! You have been pre-approved for a $500 prepaid Visa. Click the link below within 24 HOURS to claim your reward. Limited spots available!!!\n\nhttp://luxury-rewards-club.biz/claim?id=A7H2",
    receivedAt: "2026-05-10T05:30:00Z",
    category: "uncategorized",
    confidence: 0,
    status: "new",
  },
  {
    id: "e5",
    from: "Priya Anand <priya@anand-consulting.com>",
    subject: "Demo follow-up — proposing Thursday 2pm PT",
    body: "Hi,\n\nGreat chatting yesterday. As discussed, I'd like to set up a 30-minute working session with our engineering lead to walk through the API. Does Thursday May 14 at 2:00pm PT work? If not, Friday morning is also open on my end.\n\nBest,\nPriya",
    receivedAt: "2026-05-09T22:48:00Z",
    category: "uncategorized",
    confidence: 0,
    status: "new",
  },
];
